const flag = (codigoIso2) => `https://flagcdn.com/w320/${codigoIso2}.png`
const data = [
  {
    id: 1,
    nome: 'Brasil',
    siglaFifa: 'BRA',
    codigoIso2: 'br',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Brasília',
    titulosCopa: 5,
    bandeira: flag('br'),
    grupo: 'C',
  }, 
  {
    id: 2,
    nome: 'Argentina',
    siglaFifa: 'ARG',
    codigoIso2: 'ar',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Buenos Aires',
    titulosCopa: 3,
    bandeira: flag('ar'),
    grupo: 'J',
  },
  {
    id: 3,
    nome: 'Uruguai',
    siglaFifa: 'URU',
    codigoIso2: 'uy',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Montevidéu',
    titulosCopa: 2,
    bandeira: flag('uy'),
    grupo: 'H',
  },
  {
    id: 4,
    nome: 'Colômbia',
    siglaFifa: 'COL',
    codigoIso2: 'co',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Bogotá',
    titulosCopa: 0,
    bandeira: flag('co'),
    grupo: 'K',
  },
 {
    id: 5,
    nome: 'Equador',
    siglaFifa: 'ECU',
    codigoIso2: 'ec',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Quito',
    titulosCopa: 0,
    bandeira: flag('ec'),
    grupo: 'E',
  },
  {
    id: 6,
    nome: 'Paraguai',
    siglaFifa: 'PAR',
    codigoIso2: 'py',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Asunción',
    titulosCopa: 0,
    bandeira: flag('py'),
    grupo: 'D',
  },
  {
    id: 7,
    nome: 'Estados Unidos',
    siglaFifa: 'USA',
    codigoIso2: 'us',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'Washington, D.C.',
    titulosCopa: 0,
    bandeira: flag('us'),
    grupo: 'D',
  },
  {
    id: 8,
    nome: 'México',
    siglaFifa: 'MEX',
    codigoIso2: 'mx',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'Cidade do México',
    titulosCopa: 0,
    bandeira: flag('mx'),
    grupo: 'A',
  },
  {
    id: 9,
    nome: 'Canadá',
    siglaFifa: 'CAN',
    codigoIso2: 'ca',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'Ottawa',
    titulosCopa: 0,
    bandeira: flag('ca'),
    grupo: 'B',
  },
  {
    id: 10,
    nome: 'Curaçau',
    siglaFifa: 'CUW',
    codigoIso2: 'cw',
    continente: 'América Central',
    confederacao: 'CONCACAF',
    capital: 'Willemstad ',
    titulosCopa: 0,
    bandeira: flag('cw'),
    grupo: 'E',
  },

  {
    id: 11,
    nome: 'França',
    siglaFifa: 'FRA',
    codigoIso2: 'fr',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Paris',
    titulosCopa: 2,
    bandeira: flag('fr'),
    grupo: 'I',
  },
  {
    id: 12,
    nome: 'Alemanha',
    siglaFifa: 'GER',
    codigoIso2: 'de',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Berlim',
    titulosCopa: 4,
    bandeira: flag('de'),
    grupo: 'E',
  },
  {
    id: 13,
    nome: 'Espanha',
    siglaFifa: 'ESP',
    codigoIso2: 'es',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Madri',
    titulosCopa: 1,
    bandeira: flag('es'),
    grupo: 'H',
  },
  {
    id: 14,
    nome: 'Portugal',
    siglaFifa: 'POR',
    codigoIso2: 'pt',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Lisboa',
    titulosCopa: 0,
    bandeira: flag('pt'),
    grupo: 'K',
  },
  {
    id: 15,
    nome: 'Bósnia e Herzegovina',
    siglaFifa: 'BIH',
    codigoIso2: 'ba',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Sarajevo',
    titulosCopa: 0,
    bandeira: flag('ba'),
    grupo: 'B',
  },
  {
    id: 16,
    nome: 'Holanda',
    siglaFifa: 'NED',
    codigoIso2: 'nl',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Amsterdã',
    titulosCopa: 0,
    bandeira: flag('nl'),
    grupo: 'F',
  },
  {
    id: 17,
    nome: 'Bélgica',
    siglaFifa: 'BEL',
    codigoIso2: 'be',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Bruxelas',
    titulosCopa: 0,
    bandeira: flag('be'),
    grupo: 'G',
  },
  {
    id: 18,
    nome: 'Suíça',
    siglaFifa: 'SUI',
    codigoIso2: 'ch',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Berna',
    titulosCopa: 0,
    bandeira: flag('ch'),
    grupo: 'B',
  },
  {
    id: 19,
    nome: 'Croácia',
    siglaFifa: 'CRO',
    codigoIso2: 'hr',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Zagreb',
    titulosCopa: 0,
    bandeira: flag('hr'),
    grupo: 'L',
  },
  {
    id: 20,
    nome: 'Inglaterra',
    siglaFifa: 'ENG',
    codigoIso2: 'gb',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Londres',
    titulosCopa: 1,
    bandeira: flag('gb'),
    grupo: 'L',
  },
  {
    id: 21,
    nome: 'Japão',
    siglaFifa: 'JPN',
    codigoIso2: 'jp',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Tóquio',
    titulosCopa: 0,
    bandeira: flag('jp'),
    grupo: 'F',
  },
  {
    id: 22,
    nome: 'República da Coreia',
    siglaFifa: 'KOR',
    codigoIso2: 'kr',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Seul',
    titulosCopa: 0,
    bandeira: flag('kr'),
    grupo: 'A',
  },
  {
    id: 23,
    nome: 'Austrália',
    siglaFifa: 'AUS',
    codigoIso2: 'au',
    continente: 'Oceania',
    confederacao: 'AFC',
    capital: 'Canberra',
    titulosCopa: 0,
    bandeira: flag('au'),
    grupo: 'D',
  },
  {
    id: 24,
    nome: 'Arábia Saudita',
    siglaFifa: 'KSA',
    codigoIso2: 'sa',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Riad',
    titulosCopa: 0,
    bandeira: flag('sa'),
    grupo: 'H',
  },
  {
    id: 25,
    nome: 'RI do Irã',
    siglaFifa: 'IRN',
    codigoIso2: 'ir',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Teerã',
    titulosCopa: 0,
    bandeira: flag('ir'),
    grupo: 'G',
  },
  {
    id: 26,
    nome: 'Catar',
    siglaFifa: 'QAT',
    codigoIso2: 'qa',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Doha',
    titulosCopa: 0,
    bandeira: flag('qa'),
    grupo: 'B',
  },
  {
    id: 27,
    nome: 'Senegal',
    siglaFifa: 'SEN',
    codigoIso2: 'sn',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Dakar',
    titulosCopa: 0,
    bandeira: flag('sn'),
    grupo: 'I',
  },
  {
    id: 28,
    nome: 'Marrocos',
    siglaFifa: 'MAR',
    codigoIso2: 'ma',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Rabat',
    titulosCopa: 0,
    bandeira: flag('ma'),
    grupo: 'C',
  },
  {
    id: 29,
    nome: 'Argélia',
    siglaFifa: 'ALG',
    codigoIso2: 'dz',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Argel',
    titulosCopa: 0,
    bandeira: flag('dz'),
    grupo: 'J',
  },
  {
    id: 30,
    nome: 'Gana',
    siglaFifa: 'GHA',
    codigoIso2: 'gh',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Acra',
    titulosCopa: 0,
    bandeira: flag('gh'),
    grupo: 'L',
  },
  {
    id: 31,
    nome: 'Cabo Verde',
    siglaFifa: 'CPA',
    codigoIso2: 'cv',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Praia',
    titulosCopa: 0,
    bandeira: flag('cv'),
    grupo: 'H',
  },
  {
    id: 32,
    nome: 'Tunísia',
    siglaFifa: 'TUN',
    codigoIso2: 'tn',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Túnis',
    titulosCopa: 0,
    bandeira: flag('tn'),
    grupo: 'F',
  },
    {
    id: 33,
    nome: 'Haiti',
    siglaFifa: 'HAI',
    codigoIso2: 'ht',
    continente: 'América Central',
    confederacao: 'CONCACAF',
    capital: 'Port-au-Prince',
    titulosCopa: 0,
    bandeira: flag('ht'),
    grupo: 'C',
  },
    {
    id: 34,
    nome: 'Panamá',
    siglaFifa: 'PAN',
    codigoIso2: 'pa',
    continente: 'América Central',
    confederacao: 'CONCACAF',
    capital: 'Cidade do Panamá',
    titulosCopa: 0,
    bandeira: flag('pa'),
    grupo: 'L',
  },
    {
    id: 35,
    nome: 'Escócia',
    siglaFifa: 'SCO',
    codigoIso2: 'gb-sct',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Edimburgo',
    titulosCopa: 0,
    bandeira: flag('gb-sct'),
    grupo: 'C',
  },
 {
    id: 36,
    nome: 'Noruega',
    siglaFifa: 'NOR',
    codigoIso2: 'no',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Oslo',
    titulosCopa: 0,
    bandeira: flag('no'),
    grupo: 'I',
  },
  {
    id: 37,
    nome: 'Suécia',
    siglaFifa: 'SWE',
    codigoIso2: 'se',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Estocolmo',
    titulosCopa: 0,
    bandeira: flag('se'),
    grupo: 'F',
  },
  {
    id: 38,
    nome: 'Tchéquia',
    siglaFifa: 'CZE',
    codigoIso2: 'cz',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Praga',
    titulosCopa: 0,
    bandeira: flag('cz'),
    grupo: 'A',
  },
  {
    id: 39,
    nome: 'Turquia',
    siglaFifa: 'TUR',
    codigoIso2: 'tr',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Ankara',
    titulosCopa: 0,
    bandeira: flag('tr'),
    grupo: 'D',
  },
  {
    id: 40,
    nome: 'Áustria',
    siglaFifa: 'AUT',
    codigoIso2: 'at',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Viena',
    titulosCopa: 0,
    bandeira: flag('at'),
    grupo: 'J',
  },
  {
    id: 41,
    nome: 'Jordânia',
    siglaFifa: 'JOR',
    codigoIso2: 'jo',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Amman',
    titulosCopa: 0,
    bandeira: flag('jo'),
    grupo: 'J',
  },
    {
    id: 42,
    nome: 'Uzbequistão',
    siglaFifa: 'UZB',
    codigoIso2: 'uz',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Tashkent',
    titulosCopa: 0,
    bandeira: flag('uz'),
    grupo: 'K',
  },
  {
    id: 43,
    nome: 'Iraque',
    siglaFifa: 'IRQ',
    codigoIso2: 'iq',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Bagdá',
    titulosCopa: 0,
    bandeira: flag('iq'),
    grupo: 'I',
  },
  {
    id: 44,
    nome: 'Costa do Marfim',
    siglaFifa: 'CIV',
    codigoIso2: 'ci',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Yamooussoukro',
    titulosCopa: 0,
    bandeira: flag('ci'),
    grupo: 'E',
  },
 {
    id: 45,
    nome: 'Egito',
    siglaFifa: 'EGY',
    codigoIso2: 'eg',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Cairo',
    titulosCopa: 0,
    bandeira: flag('eg'),
    grupo: 'G',
  },
  {
    id: 46,
    nome: 'RD do Congo',
    siglaFifa: 'COD',
    codigoIso2: 'cd',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Kinshasa',
    titulosCopa: 0,
    bandeira: flag('cd'),
    grupo: 'K',
  },
  {
    id: 47,
    nome: 'África do Sul',
    siglaFifa: 'RSA',
    codigoIso2: 'za',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Cidade do Cabo, Bloemfontein e Pretória',
    titulosCopa: 0,
    bandeira: flag('za'),
    grupo: 'A',
  },
    {
    id: 48,
    nome: 'Nova Zelândia',
    siglaFifa: 'NZL',
    codigoIso2: 'nz',
    continente: 'África',
    confederacao: 'OFC',
    capital: 'Wellington',
    titulosCopa: 0,
    bandeira: flag('nz'),
    grupo: 'G',
  },
]
export default data