const flag = (codigoIso2) => `https://flagcdn.com/w320/${codigoIso2}.png`
const data = [
  {
    id: 1,
    nome: 'Brasil',
    siglaFifa: 'BRA',
    codigoIso2: 'br',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Brasília',
    titulosCopa: 5,
    bandeira: flag('br'),
  },
  {
    id: 2,
    nome: 'Argentina',
    siglaFifa: 'ARG',
    codigoIso2: 'ar',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Buenos Aires',
    titulosCopa: 3,
    bandeira: flag('ar'),
  },
  {
    id: 3,
    nome: 'Uruguai',
    siglaFifa: 'URU',
    codigoIso2: 'uy',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Montevidéu',
    titulosCopa: 2,
    bandeira: flag('uy'),
  },
  {
    id: 4,
    nome: 'Colômbia',
    siglaFifa: 'COL',
    codigoIso2: 'co',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Bogotá',
    titulosCopa: 0,
    bandeira: flag('co'),
  },
  {
    id: 5,
    nome: 'Chile',
    siglaFifa: 'CHI',
    codigoIso2: 'cl',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Santiago',
    titulosCopa: 0,
    bandeira: flag('cl'),
  },
  {
    id: 6,
    nome: 'Peru',
    siglaFifa: 'PER',
    codigoIso2: 'pe',
    continente: 'América do Sul',
    confederacao: 'CONMEBOL',
    capital: 'Lima',
    titulosCopa: 0,
    bandeira: flag('pe'),
  },
  {
    id: 7,
    nome: 'Estados Unidos',
    siglaFifa: 'USA',
    codigoIso2: 'us',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'Washington, D.C.',
    titulosCopa: 0,
    bandeira: flag('us'),
  },
  {
    id: 8,
    nome: 'México',
    siglaFifa: 'MEX',
    codigoIso2: 'mx',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'Cidade do México',
    titulosCopa: 0,
    bandeira: flag('mx'),
  },
  {
    id: 9,
    nome: 'Canadá',
    siglaFifa: 'CAN',
    codigoIso2: 'ca',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'Ottawa',
    titulosCopa: 0,
    bandeira: flag('ca'),
  },
  {
    id: 10,
    nome: 'Costa Rica',
    siglaFifa: 'CRC',
    codigoIso2: 'cr',
    continente: 'América do Norte',
    confederacao: 'CONCACAF',
    capital: 'San José',
    titulosCopa: 0,
    bandeira: flag('cr'),
  },
  {
    id: 11,
    nome: 'França',
    siglaFifa: 'FRA',
    codigoIso2: 'fr',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Paris',
    titulosCopa: 2,
    bandeira: flag('fr'),
  },
  {
    id: 12,
    nome: 'Alemanha',
    siglaFifa: 'GER',
    codigoIso2: 'de',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Berlim',
    titulosCopa: 4,
    bandeira: flag('de'),
  },
  {
    id: 13,
    nome: 'Espanha',
    siglaFifa: 'ESP',
    codigoIso2: 'es',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Madri',
    titulosCopa: 1,
    bandeira: flag('es'),
  },
  {
    id: 14,
    nome: 'Portugal',
    siglaFifa: 'POR',
    codigoIso2: 'pt',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Lisboa',
    titulosCopa: 0,
    bandeira: flag('pt'),
  },
  {
    id: 15,
    nome: 'Itália',
    siglaFifa: 'ITA',
    codigoIso2: 'it',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Roma',
    titulosCopa: 4,
    bandeira: flag('it'),
  },
  {
    id: 16,
    nome: 'Países Baixos',
    siglaFifa: 'NED',
    codigoIso2: 'nl',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Amsterdã',
    titulosCopa: 0,
    bandeira: flag('nl'),
  },
  {
    id: 17,
    nome: 'Bélgica',
    siglaFifa: 'BEL',
    codigoIso2: 'be',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Bruxelas',
    titulosCopa: 0,
    bandeira: flag('be'),
  },
  {
    id: 18,
    nome: 'Suíça',
    siglaFifa: 'SUI',
    codigoIso2: 'ch',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Berna',
    titulosCopa: 0,
    bandeira: flag('ch'),
  },
  {
    id: 19,
    nome: 'Croácia',
    siglaFifa: 'CRO',
    codigoIso2: 'hr',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Zagreb',
    titulosCopa: 0,
    bandeira: flag('hr'),
  },
  {
    id: 20,
    nome: 'Inglaterra',
    siglaFifa: 'ENG',
    codigoIso2: 'gb',
    continente: 'Europa',
    confederacao: 'UEFA',
    capital: 'Londres',
    titulosCopa: 1,
    bandeira: flag('gb'),
  },
  {
    id: 21,
    nome: 'Japão',
    siglaFifa: 'JPN',
    codigoIso2: 'jp',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Tóquio',
    titulosCopa: 0,
    bandeira: flag('jp'),
  },
  {
    id: 22,
    nome: 'Coreia do Sul',
    siglaFifa: 'KOR',
    codigoIso2: 'kr',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Seul',
    titulosCopa: 0,
    bandeira: flag('kr'),
  },
  {
    id: 23,
    nome: 'Austrália',
    siglaFifa: 'AUS',
    codigoIso2: 'au',
    continente: 'Oceania',
    confederacao: 'AFC',
    capital: 'Canberra',
    titulosCopa: 0,
    bandeira: flag('au'),
  },
  {
    id: 24,
    nome: 'Arábia Saudita',
    siglaFifa: 'KSA',
    codigoIso2: 'sa',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Riad',
    titulosCopa: 0,
    bandeira: flag('sa'),
  },
  {
    id: 25,
    nome: 'Irã',
    siglaFifa: 'IRN',
    codigoIso2: 'ir',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Teerã',
    titulosCopa: 0,
    bandeira: flag('ir'),
  },
  {
    id: 26,
    nome: 'Catar',
    siglaFifa: 'QAT',
    codigoIso2: 'qa',
    continente: 'Ásia',
    confederacao: 'AFC',
    capital: 'Doha',
    titulosCopa: 0,
    bandeira: flag('qa'),
  },
  {
    id: 27,
    nome: 'Senegal',
    siglaFifa: 'SEN',
    codigoIso2: 'sn',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Dakar',
    titulosCopa: 0,
    bandeira: flag('sn'),
  },
  {
    id: 28,
    nome: 'Marrocos',
    siglaFifa: 'MAR',
    codigoIso2: 'ma',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Rabat',
    titulosCopa: 0,
    bandeira: flag('ma'),
  },
  {
    id: 29,
    nome: 'Nigéria',
    siglaFifa: 'NGA',
    codigoIso2: 'ng',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Abuja',
    titulosCopa: 0,
    bandeira: flag('ng'),
  },
  {
    id: 30,
    nome: 'Gana',
    siglaFifa: 'GHA',
    codigoIso2: 'gh',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Acra',
    titulosCopa: 0,
    bandeira: flag('gh'),
  },
  {
    id: 31,
    nome: 'Camarões',
    siglaFifa: 'CMR',
    codigoIso2: 'cm',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Iaundé',
    titulosCopa: 0,
    bandeira: flag('cm'),
  },
  {
    id: 32,
    nome: 'Tunísia',
    siglaFifa: 'TUN',
    codigoIso2: 'tn',
    continente: 'África',
    confederacao: 'CAF',
    capital: 'Túnis',
    titulosCopa: 0,
    bandeira: flag('tn'),
  },
]
export default data
